// This file was auto-generated by prisma-generator-typescript-interfaces

export type user_role = "ADMIN" | "DOSEN" | "PENERBIT";

export interface Major {
  id: number;
  major_name: string;
  major_description: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  users?: User[];
}

export interface User {
  id: number;
  name: string;
  email: string;
  password: string;
  role: user_role;
  major_id: number | null;
  major?: Major | null;
  nidn: string | null;
  address: string | null;
  phone_number: bigint | null;
  profile_pic: string | null;
  publications?: Publication[];
  publisherPublication?: Publication[];
  activities?: PublicationActivity[];
  transactions?: Transaction[];
  transactionLogs?: TransactionLog[];
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
}

export interface PublicationStatus {
  id: number;
  status_name: string;
  status_description: string | null;
  publications?: Publication[];
  activities?: PublicationActivity[];
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
}

export interface Publication {
  id: number;
  user_id: number;
  publisher_id: number | null;
  lecturer?: User;
  publisher?: User | null;
  status?: PublicationStatus;
  activities?: PublicationActivity[];
  items?: TransactionItem[];
  publication_ticket: string;
  publication_title: string;
  publication_document: string;
  publication_book_cover: string | null;
  publication_authenticity_proof: string | null;
  current_status_id: number;
  supporting_url: string | null;
  is_invoice: boolean;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
}

export interface PublicationActivity {
  id: number;
  publication_id: number;
  user_id: number;
  publication_status_id: number;
  publication?: Publication;
  user?: User;
  status?: PublicationStatus;
  publication_notes: string | null;
  publication_document_url: string | null;
  supporting_url: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
}

export interface Transaction {
  id: number;
  user_id: number;
  current_status_id: number;
  payment_proof: string | null;
  transaction_ticket: string | null;
  transaction_notes: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  user?: User;
  status?: TransactionStatus;
  items?: TransactionItem[];
  logs?: TransactionLog[];
}

export interface TransactionItem {
  id: number;
  transaction_id: number;
  publication_id: number;
  cost: number;
  quantity: number;
  total_cost: number;
  transaction?: Transaction;
  publication?: Publication;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
}

export interface TransactionLog {
  id: number;
  transaction_id: number;
  transaction_status_id: number;
  user_id: number | null;
  note: string | null;
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
  transaction?: Transaction;
  user?: User | null;
  status?: TransactionStatus;
}

export interface TransactionStatus {
  id: number;
  status_name: string;
  transaction?: Transaction[];
  logs?: TransactionLog[];
  createdAt: Date;
  updatedAt: Date;
  deleted: boolean;
}
